name: Node.js CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: <%= pm %>-cache
        with:
          path:  "**/node_modules"
          key: ${{ runner.os }}-<%= pm %>-${{ hashFiles('**/<%= pm === 'npm' ? 'package-lock.json' : 'yarn.lock' %>') }}
      - run: <%= pm %> install
        if: steps.<%= pm %>-cache.outputs.cache-hit != 'true'
      - run: <%= pm === 'npm' ? 'npm install --prefix server' : 'yarn install --cwd server' %>
        if: steps.<%= pm %>-cache.outputs.cache-hit != 'true'
      - run: <%= pm %><%= pm === 'npm' ? ' run' : '' %> lint
      - run: <%= pm %><%= pm === 'npm' ? ' run' : '' %> typecheck<% if (testing !== 'none') { %>
      - run: <%= pm %> test<% } %>
