name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS:${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest]
        include:
          - os: windows-latest
            node-version: 14
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
        if: matrix.os != 'windows-latest'
      - run: NODE_ENV=test yarn build
        if: matrix.os == 'ubuntu-latest'
      - run: $env:NODE_ENV="test"; yarn build
        if: matrix.os == 'windows-latest'
      - run: yarn typecheck

      - run: |
          sudo systemctl start mysql.service
          node bin/index.js --answers '{"dir":"../nextjs","daemon":"pm2","dbUser":"root","dbPass":"root","dbName":"test","testing":"jest"}'
        if: matrix.os == 'ubuntu-latest'
      - run: node bin/index.js --answers '{\"dir\":\"../nextjs\",\"daemon\":\"pm2\",\"prismaDB\":\"sqlite\",\"dbUser\":\"root\",\"dbPass\":\"root\",\"dbName\":\"test\",\"testing\":\"jest\"}'
        if: matrix.os == 'windows-latest'
      - run: npm run lint --prefix ../nextjs
      - run: npm run typecheck --prefix ../nextjs
      - run: npm run test --prefix ../nextjs
      - run: npm run build --prefix ../nextjs/server
      - run: npm run pm2:start --prefix ../nextjs/server

      - run: yarn test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: snapshot
          path: ./server/__test__/forArtifact.md

      - run: node bin/index.js --answers '{"dir":"../nextjs-typeorm","orm":"typeorm","testing":"jest"}'
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 10
      - run: npm run lint --prefix ../nextjs-typeorm
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 10
      - run: npm run typecheck --prefix ../nextjs-typeorm
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 10
      - run: npm run test --prefix ../nextjs-typeorm
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 10

      - run: node bin/index.js --answers '{"dir":"../nuxtjs","prismaDB":"sqlite","testing":"jest"}'
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 12
      - run: npm run lint --prefix ../nuxtjs
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 12
      - run: npm run typecheck --prefix ../nuxtjs
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 12
      - run: npm run test --prefix ../nuxtjs
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 12

      - run: node bin/index.js --answers '{"dir":"../sapper","prismaDB":"sqlite","testing":"jest"}'
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 14
      - run: npm run lint --prefix ../sapper
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 14
      - run: npm run typecheck --prefix ../sapper
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 14
      - run: npm run test --prefix ../sapper
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 14

  release:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v12-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
